[theme]
primaryColor = "#C8102E"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F9FAFB"
textColor = "#111827"
font = "sans serif"

[server]
maxUploadSize = 500
enableXsrfProtection = true

[browser]
gatherUsageStats = false
